/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: rage.i

package rage

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
extern void _wrap_Swig_free_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_rage_a350b1ffd789f23c(swig_intgo arg1);
extern uintptr_t _wrap_time_t_GetHour_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_time_t_GetMinute_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_time_t_GetSecond_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_new_time_t_rage_a350b1ffd789f23c(void);
extern void _wrap_delete_time_t_rage_a350b1ffd789f23c(uintptr_t arg1);
extern swig_intgo _wrap_IPlugin_sdkver_IPlugin_rage_a350b1ffd789f23c(void);
extern uintptr_t _wrap_IPlugin_GetVersion_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_IPlugin_Unload_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_new_IPlugin_rage_a350b1ffd789f23c(void);
extern void _wrap_delete_IPlugin_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IEventHandler_GetEntityHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IEventHandler_GetPlayerHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IEventHandler_GetVehicleHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IEventHandler_GetColshapeHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IEventHandler_GetCheckpointHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IEventHandler_GetBlipHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IEventHandler_GetStreamerHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IEventHandler_GetTickHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_new_IEventHandler_rage_a350b1ffd789f23c(void);
extern void _wrap_delete_IEventHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_IEntityHandler_OnEntityCreated_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_IEntityHandler_OnEntityDestroyed_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_IEntityHandler_OnEntityModelChange_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_new_IEntityHandler_rage_a350b1ffd789f23c(void);
extern void _wrap_delete_IEntityHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern swig_intgo _wrap_exit_t_disconnect_rage_a350b1ffd789f23c(void);
extern swig_intgo _wrap_exit_t_timeout_rage_a350b1ffd789f23c(void);
extern swig_intgo _wrap_exit_t_kicked_rage_a350b1ffd789f23c(void);
extern void _wrap_IPlayerHandler_OnPlayerJoin_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_IPlayerHandler_OnPlayerReady_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_IPlayerHandler_OnPlayerQuit_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3, swig_type_1 arg4);
extern void _wrap_IPlayerHandler_OnPlayerCommand_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_IPlayerHandler_OnPlayerChat_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_IPlayerHandler_OnPlayerDeath_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern void _wrap_IPlayerHandler_OnPlayerSpawn_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_IPlayerHandler_OnPlayerDamage_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, float arg3, float arg4);
extern void _wrap_IPlayerHandler_OnPlayerWeaponChange_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern void _wrap_IPlayerHandler_OnPlayerRemoteEvent_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern void _wrap_IPlayerHandler_OnPlayerStartEnterVehicle_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern void _wrap_IPlayerHandler_OnPlayerEnterVehicle_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern void _wrap_IPlayerHandler_OnPlayerStartExitVehicle_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_IPlayerHandler_OnPlayerExitVehicle_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_new_IPlayerHandler_rage_a350b1ffd789f23c(void);
extern void _wrap_delete_IPlayerHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_IVehicleHandler_OnVehicleDeath_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern void _wrap_IVehicleHandler_OnVehicleSirenToggle_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, _Bool arg3);
extern void _wrap_IVehicleHandler_OnVehicleHornToggle_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, _Bool arg3);
extern void _wrap_IVehicleHandler_OnTrailerAttached_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_IVehicleHandler_OnVehicleDamage_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, float arg3, float arg4);
extern uintptr_t _wrap_new_IVehicleHandler_rage_a350b1ffd789f23c(void);
extern void _wrap_delete_IVehicleHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_IColshapeHandler_OnPlayerEnterColshape_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_IColshapeHandler_OnPlayerExitColshape_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_new_IColshapeHandler_rage_a350b1ffd789f23c(void);
extern void _wrap_delete_IColshapeHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_ICheckpointHandler_OnPlayerEnterCheckpoint_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_ICheckpointHandler_OnPlayerExitCheckpoint_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_new_ICheckpointHandler_rage_a350b1ffd789f23c(void);
extern void _wrap_delete_ICheckpointHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_IBlipHandler_OnPlayerCreateWaypoint_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_IBlipHandler_OnPlayerReachWaypoint_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_new_IBlipHandler_rage_a350b1ffd789f23c(void);
extern void _wrap_delete_IBlipHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_IStreamerHandler_OnPlayerStreamIn_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_IStreamerHandler_OnPlayerStreamOut_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_new_IStreamerHandler_rage_a350b1ffd789f23c(void);
extern void _wrap_delete_IStreamerHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_ITickHandler_Tick_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_new_ITickHandler_rage_a350b1ffd789f23c(void);
extern void _wrap_delete_ITickHandler_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IWorld_GetTime_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_IWorld_SetTime_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_IWorld_GetWeather_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_IWorld_SetWeather_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_IWorld_SetWeatherTransition__SWIG_0_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, float arg3);
extern void _wrap_IWorld_SetWeatherTransition__SWIG_1_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_IWorld_RequestIpl_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_IWorld_RemoveIpl_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern _Bool _wrap_IWorld_AreTrafficLightsLocked_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_IWorld_LockTrafficLights_rage_a350b1ffd789f23c(uintptr_t arg1, _Bool arg2);
extern swig_intgo _wrap_IWorld_GetTrafficLightsState_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_IWorld_SetTrafficLightsState_rage_a350b1ffd789f23c(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_delete_IWorld_rage_a350b1ffd789f23c(uintptr_t arg1);
extern swig_intgo _wrap_IConfig_GetInt__SWIG_0_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3);
extern swig_intgo _wrap_IConfig_GetInt__SWIG_1_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_IConfig_GetString__SWIG_0_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_IConfig_GetString__SWIG_1_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_delete_IConfig_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IMultiplayer_FromPointer_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_IMultiplayer_AddEventHandler_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_IMultiplayer_AddRemoteEventHandler_rage_a350b1ffd789f23c(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_IMultiplayer_GetPlayerPool_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IMultiplayer_GetVehiclePool_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IMultiplayer_GetColshapePool_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IMultiplayer_GetCheckpointPool_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IMultiplayer_GetMarkerPool_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IMultiplayer_GetBlipPool_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IMultiplayer_GetPickupPool_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IMultiplayer_GetObjectPool_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IMultiplayer_GetLabelPool_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IMultiplayer_GetWorld_rage_a350b1ffd789f23c(uintptr_t arg1);
extern uintptr_t _wrap_IMultiplayer_GetConfig_rage_a350b1ffd789f23c(uintptr_t arg1);
extern void _wrap_delete_IMultiplayer_rage_a350b1ffd789f23c(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_rage_a350b1ffd789f23c(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrTime_t uintptr

func (p SwigcptrTime_t) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTime_t) SwigIsTime_t() {
}

func Time_tGetHour(arg1 Time_t) (_swig_ret Uint8_t) {
	var swig_r Uint8_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint8_t)(SwigcptrUint8_t(C._wrap_time_t_GetHour_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Time_tGetMinute(arg1 Time_t) (_swig_ret Uint8_t) {
	var swig_r Uint8_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint8_t)(SwigcptrUint8_t(C._wrap_time_t_GetMinute_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Time_tGetSecond(arg1 Time_t) (_swig_ret Uint8_t) {
	var swig_r Uint8_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint8_t)(SwigcptrUint8_t(C._wrap_time_t_GetSecond_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewTime_t() (_swig_ret Time_t) {
	var swig_r Time_t
	swig_r = (Time_t)(SwigcptrTime_t(C._wrap_new_time_t_rage_a350b1ffd789f23c()))
	return swig_r
}

func DeleteTime_t(arg1 Time_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_time_t_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type Time_t interface {
	Swigcptr() uintptr
	SwigIsTime_t()
}

type SwigcptrIPlugin uintptr

func (p SwigcptrIPlugin) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIPlugin) SwigIsIPlugin() {
}

func _swig_getIPlugin_IPlugin_sdkver_IPlugin() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_IPlugin_sdkver_IPlugin_rage_a350b1ffd789f23c())
	return swig_r
}

var IPluginSdkver int = _swig_getIPlugin_IPlugin_sdkver_IPlugin()
func (arg1 SwigcptrIPlugin) GetVersion() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_IPlugin_GetVersion_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIPlugin) Unload() {
	_swig_i_0 := arg1
	C._wrap_IPlugin_Unload_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

func NewIPlugin() (_swig_ret IPlugin) {
	var swig_r IPlugin
	swig_r = (IPlugin)(SwigcptrIPlugin(C._wrap_new_IPlugin_rage_a350b1ffd789f23c()))
	return swig_r
}

func DeleteIPlugin(arg1 IPlugin) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IPlugin_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type IPlugin interface {
	Swigcptr() uintptr
	SwigIsIPlugin()
	GetVersion() (_swig_ret Uint32_t)
	Unload()
}

type SwigcptrIEventHandler uintptr

func (p SwigcptrIEventHandler) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIEventHandler) SwigIsIEventHandler() {
}

func (arg1 SwigcptrIEventHandler) GetEntityHandler() (_swig_ret IEntityHandler) {
	var swig_r IEntityHandler
	_swig_i_0 := arg1
	swig_r = (IEntityHandler)(SwigcptrIEntityHandler(C._wrap_IEventHandler_GetEntityHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIEventHandler) GetPlayerHandler() (_swig_ret IPlayerHandler) {
	var swig_r IPlayerHandler
	_swig_i_0 := arg1
	swig_r = (IPlayerHandler)(SwigcptrIPlayerHandler(C._wrap_IEventHandler_GetPlayerHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIEventHandler) GetVehicleHandler() (_swig_ret IVehicleHandler) {
	var swig_r IVehicleHandler
	_swig_i_0 := arg1
	swig_r = (IVehicleHandler)(SwigcptrIVehicleHandler(C._wrap_IEventHandler_GetVehicleHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIEventHandler) GetColshapeHandler() (_swig_ret IColshapeHandler) {
	var swig_r IColshapeHandler
	_swig_i_0 := arg1
	swig_r = (IColshapeHandler)(SwigcptrIColshapeHandler(C._wrap_IEventHandler_GetColshapeHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIEventHandler) GetCheckpointHandler() (_swig_ret ICheckpointHandler) {
	var swig_r ICheckpointHandler
	_swig_i_0 := arg1
	swig_r = (ICheckpointHandler)(SwigcptrICheckpointHandler(C._wrap_IEventHandler_GetCheckpointHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIEventHandler) GetBlipHandler() (_swig_ret IBlipHandler) {
	var swig_r IBlipHandler
	_swig_i_0 := arg1
	swig_r = (IBlipHandler)(SwigcptrIBlipHandler(C._wrap_IEventHandler_GetBlipHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIEventHandler) GetStreamerHandler() (_swig_ret IStreamerHandler) {
	var swig_r IStreamerHandler
	_swig_i_0 := arg1
	swig_r = (IStreamerHandler)(SwigcptrIStreamerHandler(C._wrap_IEventHandler_GetStreamerHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIEventHandler) GetTickHandler() (_swig_ret ITickHandler) {
	var swig_r ITickHandler
	_swig_i_0 := arg1
	swig_r = (ITickHandler)(SwigcptrITickHandler(C._wrap_IEventHandler_GetTickHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewIEventHandler() (_swig_ret IEventHandler) {
	var swig_r IEventHandler
	swig_r = (IEventHandler)(SwigcptrIEventHandler(C._wrap_new_IEventHandler_rage_a350b1ffd789f23c()))
	return swig_r
}

func DeleteIEventHandler(arg1 IEventHandler) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IEventHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type IEventHandler interface {
	Swigcptr() uintptr
	SwigIsIEventHandler()
	GetEntityHandler() (_swig_ret IEntityHandler)
	GetPlayerHandler() (_swig_ret IPlayerHandler)
	GetVehicleHandler() (_swig_ret IVehicleHandler)
	GetColshapeHandler() (_swig_ret IColshapeHandler)
	GetCheckpointHandler() (_swig_ret ICheckpointHandler)
	GetBlipHandler() (_swig_ret IBlipHandler)
	GetStreamerHandler() (_swig_ret IStreamerHandler)
	GetTickHandler() (_swig_ret ITickHandler)
}

type SwigcptrIEntityHandler uintptr

func (p SwigcptrIEntityHandler) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIEntityHandler) SwigIsIEntityHandler() {
}

func (arg1 SwigcptrIEntityHandler) OnEntityCreated(arg2 IEntity) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IEntityHandler_OnEntityCreated_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIEntityHandler) OnEntityDestroyed(arg2 IEntity) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IEntityHandler_OnEntityDestroyed_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIEntityHandler) OnEntityModelChange(arg2 IEntity, arg3 Hash_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IEntityHandler_OnEntityModelChange_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func NewIEntityHandler() (_swig_ret IEntityHandler) {
	var swig_r IEntityHandler
	swig_r = (IEntityHandler)(SwigcptrIEntityHandler(C._wrap_new_IEntityHandler_rage_a350b1ffd789f23c()))
	return swig_r
}

func DeleteIEntityHandler(arg1 IEntityHandler) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IEntityHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type IEntityHandler interface {
	Swigcptr() uintptr
	SwigIsIEntityHandler()
	OnEntityCreated(arg2 IEntity)
	OnEntityDestroyed(arg2 IEntity)
	OnEntityModelChange(arg2 IEntity, arg3 Hash_t)
}

type RageExit_t int
func _swig_getexit_t_disconnect() (_swig_ret RageExit_t) {
	var swig_r RageExit_t
	swig_r = (RageExit_t)(C._wrap_exit_t_disconnect_rage_a350b1ffd789f23c())
	return swig_r
}

var Exit_t_disconnect RageExit_t = _swig_getexit_t_disconnect()
func _swig_getexit_t_timeout() (_swig_ret RageExit_t) {
	var swig_r RageExit_t
	swig_r = (RageExit_t)(C._wrap_exit_t_timeout_rage_a350b1ffd789f23c())
	return swig_r
}

var Exit_t_timeout RageExit_t = _swig_getexit_t_timeout()
func _swig_getexit_t_kicked() (_swig_ret RageExit_t) {
	var swig_r RageExit_t
	swig_r = (RageExit_t)(C._wrap_exit_t_kicked_rage_a350b1ffd789f23c())
	return swig_r
}

var Exit_t_kicked RageExit_t = _swig_getexit_t_kicked()
type SwigcptrIPlayerHandler uintptr

func (p SwigcptrIPlayerHandler) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIPlayerHandler) SwigIsIPlayerHandler() {
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerJoin(arg2 IPlayer) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IPlayerHandler_OnPlayerJoin_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerReady(arg2 IPlayer) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IPlayerHandler_OnPlayerReady_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerQuit(arg2 IPlayer, arg3 RageExit_t, arg4 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_IPlayerHandler_OnPlayerQuit_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerCommand(arg2 IPlayer, arg3 Std_u16string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IPlayerHandler_OnPlayerCommand_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerChat(arg2 IPlayer, arg3 Std_u16string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IPlayerHandler_OnPlayerChat_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerDeath(arg2 IPlayer, arg3 Hash_t, arg4 IPlayer) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	C._wrap_IPlayerHandler_OnPlayerDeath_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerSpawn(arg2 IPlayer) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IPlayerHandler_OnPlayerSpawn_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerDamage(arg2 IPlayer, arg3 float32, arg4 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_IPlayerHandler_OnPlayerDamage_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.float(_swig_i_2), C.float(_swig_i_3))
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerWeaponChange(arg2 IPlayer, arg3 Hash_t, arg4 Hash_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	C._wrap_IPlayerHandler_OnPlayerWeaponChange_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerRemoteEvent(arg2 IPlayer, arg3 Uint64_t, arg4 Args_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	C._wrap_IPlayerHandler_OnPlayerRemoteEvent_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerStartEnterVehicle(arg2 IPlayer, arg3 IVehicle, arg4 Uint8_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	C._wrap_IPlayerHandler_OnPlayerStartEnterVehicle_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerEnterVehicle(arg2 IPlayer, arg3 IVehicle, arg4 Uint8_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	C._wrap_IPlayerHandler_OnPlayerEnterVehicle_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerStartExitVehicle(arg2 IPlayer, arg3 IVehicle) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IPlayerHandler_OnPlayerStartExitVehicle_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrIPlayerHandler) OnPlayerExitVehicle(arg2 IPlayer, arg3 IVehicle) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IPlayerHandler_OnPlayerExitVehicle_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func NewIPlayerHandler() (_swig_ret IPlayerHandler) {
	var swig_r IPlayerHandler
	swig_r = (IPlayerHandler)(SwigcptrIPlayerHandler(C._wrap_new_IPlayerHandler_rage_a350b1ffd789f23c()))
	return swig_r
}

func DeleteIPlayerHandler(arg1 IPlayerHandler) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IPlayerHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type IPlayerHandler interface {
	Swigcptr() uintptr
	SwigIsIPlayerHandler()
	OnPlayerJoin(arg2 IPlayer)
	OnPlayerReady(arg2 IPlayer)
	OnPlayerQuit(arg2 IPlayer, arg3 RageExit_t, arg4 string)
	OnPlayerCommand(arg2 IPlayer, arg3 Std_u16string)
	OnPlayerChat(arg2 IPlayer, arg3 Std_u16string)
	OnPlayerDeath(arg2 IPlayer, arg3 Hash_t, arg4 IPlayer)
	OnPlayerSpawn(arg2 IPlayer)
	OnPlayerDamage(arg2 IPlayer, arg3 float32, arg4 float32)
	OnPlayerWeaponChange(arg2 IPlayer, arg3 Hash_t, arg4 Hash_t)
	OnPlayerRemoteEvent(arg2 IPlayer, arg3 Uint64_t, arg4 Args_t)
	OnPlayerStartEnterVehicle(arg2 IPlayer, arg3 IVehicle, arg4 Uint8_t)
	OnPlayerEnterVehicle(arg2 IPlayer, arg3 IVehicle, arg4 Uint8_t)
	OnPlayerStartExitVehicle(arg2 IPlayer, arg3 IVehicle)
	OnPlayerExitVehicle(arg2 IPlayer, arg3 IVehicle)
}

type SwigcptrIVehicleHandler uintptr

func (p SwigcptrIVehicleHandler) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIVehicleHandler) SwigIsIVehicleHandler() {
}

func (arg1 SwigcptrIVehicleHandler) OnVehicleDeath(arg2 IVehicle, arg3 Hash_t, arg4 IPlayer) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	C._wrap_IVehicleHandler_OnVehicleDeath_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))
}

func (arg1 SwigcptrIVehicleHandler) OnVehicleSirenToggle(arg2 IVehicle, arg3 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_IVehicleHandler_OnVehicleSirenToggle_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C._Bool(_swig_i_2))
}

func (arg1 SwigcptrIVehicleHandler) OnVehicleHornToggle(arg2 IVehicle, arg3 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_IVehicleHandler_OnVehicleHornToggle_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C._Bool(_swig_i_2))
}

func (arg1 SwigcptrIVehicleHandler) OnTrailerAttached(arg2 IVehicle, arg3 IVehicle) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IVehicleHandler_OnTrailerAttached_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrIVehicleHandler) OnVehicleDamage(arg2 IVehicle, arg3 float32, arg4 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_IVehicleHandler_OnVehicleDamage_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.float(_swig_i_2), C.float(_swig_i_3))
}

func NewIVehicleHandler() (_swig_ret IVehicleHandler) {
	var swig_r IVehicleHandler
	swig_r = (IVehicleHandler)(SwigcptrIVehicleHandler(C._wrap_new_IVehicleHandler_rage_a350b1ffd789f23c()))
	return swig_r
}

func DeleteIVehicleHandler(arg1 IVehicleHandler) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IVehicleHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type IVehicleHandler interface {
	Swigcptr() uintptr
	SwigIsIVehicleHandler()
	OnVehicleDeath(arg2 IVehicle, arg3 Hash_t, arg4 IPlayer)
	OnVehicleSirenToggle(arg2 IVehicle, arg3 bool)
	OnVehicleHornToggle(arg2 IVehicle, arg3 bool)
	OnTrailerAttached(arg2 IVehicle, arg3 IVehicle)
	OnVehicleDamage(arg2 IVehicle, arg3 float32, arg4 float32)
}

type SwigcptrIColshapeHandler uintptr

func (p SwigcptrIColshapeHandler) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIColshapeHandler) SwigIsIColshapeHandler() {
}

func (arg1 SwigcptrIColshapeHandler) OnPlayerEnterColshape(arg2 IPlayer, arg3 IColshape) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IColshapeHandler_OnPlayerEnterColshape_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrIColshapeHandler) OnPlayerExitColshape(arg2 IPlayer, arg3 IColshape) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IColshapeHandler_OnPlayerExitColshape_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func NewIColshapeHandler() (_swig_ret IColshapeHandler) {
	var swig_r IColshapeHandler
	swig_r = (IColshapeHandler)(SwigcptrIColshapeHandler(C._wrap_new_IColshapeHandler_rage_a350b1ffd789f23c()))
	return swig_r
}

func DeleteIColshapeHandler(arg1 IColshapeHandler) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IColshapeHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type IColshapeHandler interface {
	Swigcptr() uintptr
	SwigIsIColshapeHandler()
	OnPlayerEnterColshape(arg2 IPlayer, arg3 IColshape)
	OnPlayerExitColshape(arg2 IPlayer, arg3 IColshape)
}

type SwigcptrICheckpointHandler uintptr

func (p SwigcptrICheckpointHandler) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrICheckpointHandler) SwigIsICheckpointHandler() {
}

func (arg1 SwigcptrICheckpointHandler) OnPlayerEnterCheckpoint(arg2 IPlayer, arg3 ICheckpoint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_ICheckpointHandler_OnPlayerEnterCheckpoint_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrICheckpointHandler) OnPlayerExitCheckpoint(arg2 IPlayer, arg3 ICheckpoint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_ICheckpointHandler_OnPlayerExitCheckpoint_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func NewICheckpointHandler() (_swig_ret ICheckpointHandler) {
	var swig_r ICheckpointHandler
	swig_r = (ICheckpointHandler)(SwigcptrICheckpointHandler(C._wrap_new_ICheckpointHandler_rage_a350b1ffd789f23c()))
	return swig_r
}

func DeleteICheckpointHandler(arg1 ICheckpointHandler) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_ICheckpointHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type ICheckpointHandler interface {
	Swigcptr() uintptr
	SwigIsICheckpointHandler()
	OnPlayerEnterCheckpoint(arg2 IPlayer, arg3 ICheckpoint)
	OnPlayerExitCheckpoint(arg2 IPlayer, arg3 ICheckpoint)
}

type SwigcptrIBlipHandler uintptr

func (p SwigcptrIBlipHandler) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIBlipHandler) SwigIsIBlipHandler() {
}

func (arg1 SwigcptrIBlipHandler) OnPlayerCreateWaypoint(arg2 Rage_IPlayer, arg3 Vector3) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IBlipHandler_OnPlayerCreateWaypoint_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrIBlipHandler) OnPlayerReachWaypoint(arg2 Rage_IPlayer) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IBlipHandler_OnPlayerReachWaypoint_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func NewIBlipHandler() (_swig_ret IBlipHandler) {
	var swig_r IBlipHandler
	swig_r = (IBlipHandler)(SwigcptrIBlipHandler(C._wrap_new_IBlipHandler_rage_a350b1ffd789f23c()))
	return swig_r
}

func DeleteIBlipHandler(arg1 IBlipHandler) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IBlipHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type IBlipHandler interface {
	Swigcptr() uintptr
	SwigIsIBlipHandler()
	OnPlayerCreateWaypoint(arg2 Rage_IPlayer, arg3 Vector3)
	OnPlayerReachWaypoint(arg2 Rage_IPlayer)
}

type SwigcptrIStreamerHandler uintptr

func (p SwigcptrIStreamerHandler) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIStreamerHandler) SwigIsIStreamerHandler() {
}

func (arg1 SwigcptrIStreamerHandler) OnPlayerStreamIn(arg2 IPlayer, arg3 IPlayer) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IStreamerHandler_OnPlayerStreamIn_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrIStreamerHandler) OnPlayerStreamOut(arg2 IPlayer, arg3 IPlayer) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IStreamerHandler_OnPlayerStreamOut_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func NewIStreamerHandler() (_swig_ret IStreamerHandler) {
	var swig_r IStreamerHandler
	swig_r = (IStreamerHandler)(SwigcptrIStreamerHandler(C._wrap_new_IStreamerHandler_rage_a350b1ffd789f23c()))
	return swig_r
}

func DeleteIStreamerHandler(arg1 IStreamerHandler) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IStreamerHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type IStreamerHandler interface {
	Swigcptr() uintptr
	SwigIsIStreamerHandler()
	OnPlayerStreamIn(arg2 IPlayer, arg3 IPlayer)
	OnPlayerStreamOut(arg2 IPlayer, arg3 IPlayer)
}

type SwigcptrITickHandler uintptr

func (p SwigcptrITickHandler) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrITickHandler) SwigIsITickHandler() {
}

func (arg1 SwigcptrITickHandler) Tick() {
	_swig_i_0 := arg1
	C._wrap_ITickHandler_Tick_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

func NewITickHandler() (_swig_ret ITickHandler) {
	var swig_r ITickHandler
	swig_r = (ITickHandler)(SwigcptrITickHandler(C._wrap_new_ITickHandler_rage_a350b1ffd789f23c()))
	return swig_r
}

func DeleteITickHandler(arg1 ITickHandler) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_ITickHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type ITickHandler interface {
	Swigcptr() uintptr
	SwigIsITickHandler()
	Tick()
}

type SwigcptrIWorld uintptr

func (p SwigcptrIWorld) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIWorld) SwigIsIWorld() {
}

func (arg1 SwigcptrIWorld) GetTime() (_swig_ret Time_t) {
	var swig_r Time_t
	_swig_i_0 := arg1
	swig_r = (Time_t)(SwigcptrTime_t(C._wrap_IWorld_GetTime_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIWorld) SetTime(arg2 Time_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IWorld_SetTime_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIWorld) GetWeather() (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_IWorld_GetWeather_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIWorld) SetWeather(arg2 Std_string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IWorld_SetWeather_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIWorld) SetWeatherTransition__SWIG_0(arg2 Std_string, arg3 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_IWorld_SetWeatherTransition__SWIG_0_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.float(_swig_i_2))
}

func (arg1 SwigcptrIWorld) SetWeatherTransition__SWIG_1(arg2 Std_string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IWorld_SetWeatherTransition__SWIG_1_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (p SwigcptrIWorld) SetWeatherTransition(a ...interface{}) {
	argc := len(a)
	if argc == 1 {
		p.SetWeatherTransition__SWIG_1(a[0].(Std_string))
		return
	}
	if argc == 2 {
		p.SetWeatherTransition__SWIG_0(a[0].(Std_string), a[1].(float32))
		return
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrIWorld) RequestIpl(arg2 Std_string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IWorld_RequestIpl_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIWorld) RemoveIpl(arg2 Std_string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IWorld_RemoveIpl_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIWorld) AreTrafficLightsLocked() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_IWorld_AreTrafficLightsLocked_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIWorld) LockTrafficLights(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IWorld_LockTrafficLights_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrIWorld) GetTrafficLightsState() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_IWorld_GetTrafficLightsState_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIWorld) SetTrafficLightsState(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IWorld_SetTrafficLightsState_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func DeleteIWorld(arg1 IWorld) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IWorld_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type IWorld interface {
	Swigcptr() uintptr
	SwigIsIWorld()
	GetTime() (_swig_ret Time_t)
	SetTime(arg2 Time_t)
	GetWeather() (_swig_ret Std_string)
	SetWeather(arg2 Std_string)
	SetWeatherTransition(a ...interface{})
	RequestIpl(arg2 Std_string)
	RemoveIpl(arg2 Std_string)
	AreTrafficLightsLocked() (_swig_ret bool)
	LockTrafficLights(arg2 bool)
	GetTrafficLightsState() (_swig_ret int)
	SetTrafficLightsState(arg2 int)
}

type SwigcptrIConfig uintptr

func (p SwigcptrIConfig) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIConfig) SwigIsIConfig() {
}

func (arg1 SwigcptrIConfig) GetInt__SWIG_0(arg2 Std_string, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_IConfig_GetInt__SWIG_0_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func (arg1 SwigcptrIConfig) GetInt__SWIG_1(arg2 Std_string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_IConfig_GetInt__SWIG_1_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (p SwigcptrIConfig) GetInt(a ...interface{}) int {
	argc := len(a)
	if argc == 1 {
		return p.GetInt__SWIG_1(a[0].(Std_string))
	}
	if argc == 2 {
		return p.GetInt__SWIG_0(a[0].(Std_string), a[1].(int))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrIConfig) GetString__SWIG_0(arg2 Std_string, arg3 Std_string) (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_IConfig_GetString__SWIG_0_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}

func (arg1 SwigcptrIConfig) GetString__SWIG_1(arg2 Std_string) (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_IConfig_GetString__SWIG_1_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (p SwigcptrIConfig) GetString(a ...interface{}) Std_string {
	argc := len(a)
	if argc == 1 {
		return p.GetString__SWIG_1(a[0].(Std_string))
	}
	if argc == 2 {
		return p.GetString__SWIG_0(a[0].(Std_string), a[1].(Std_string))
	}
	panic("No match for overloaded function call")
}

func DeleteIConfig(arg1 IConfig) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IConfig_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type IConfig interface {
	Swigcptr() uintptr
	SwigIsIConfig()
	GetInt(a ...interface{}) int
	GetString(a ...interface{}) Std_string
}

type SwigcptrIMultiplayer uintptr

func (p SwigcptrIMultiplayer) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIMultiplayer) SwigIsIMultiplayer() {
}

func IMultiplayerFromPointer(arg1 uintptr) (_swig_ret IMultiplayer) {
	var swig_r IMultiplayer
	_swig_i_0 := arg1
	swig_r = (IMultiplayer)(SwigcptrIMultiplayer(C._wrap_IMultiplayer_FromPointer_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIMultiplayer) AddEventHandler(arg2 IEventHandler) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_IMultiplayer_AddEventHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrIMultiplayer) AddRemoteEventHandler(arg2 Std_string, arg3 Std_function_Sl_void_Sp_IPlayer_Sm__Sc_args_t_SS_const_SA__SP__Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_IMultiplayer_AddRemoteEventHandler_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrIMultiplayer) GetPlayerPool() (_swig_ret IPlayerPool) {
	var swig_r IPlayerPool
	_swig_i_0 := arg1
	swig_r = (IPlayerPool)(SwigcptrIPlayerPool(C._wrap_IMultiplayer_GetPlayerPool_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIMultiplayer) GetVehiclePool() (_swig_ret IVehiclePool) {
	var swig_r IVehiclePool
	_swig_i_0 := arg1
	swig_r = (IVehiclePool)(SwigcptrIVehiclePool(C._wrap_IMultiplayer_GetVehiclePool_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIMultiplayer) GetColshapePool() (_swig_ret IColshapePool) {
	var swig_r IColshapePool
	_swig_i_0 := arg1
	swig_r = (IColshapePool)(SwigcptrIColshapePool(C._wrap_IMultiplayer_GetColshapePool_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIMultiplayer) GetCheckpointPool() (_swig_ret ICheckpointPool) {
	var swig_r ICheckpointPool
	_swig_i_0 := arg1
	swig_r = (ICheckpointPool)(SwigcptrICheckpointPool(C._wrap_IMultiplayer_GetCheckpointPool_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIMultiplayer) GetMarkerPool() (_swig_ret IMarkerPool) {
	var swig_r IMarkerPool
	_swig_i_0 := arg1
	swig_r = (IMarkerPool)(SwigcptrIMarkerPool(C._wrap_IMultiplayer_GetMarkerPool_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIMultiplayer) GetBlipPool() (_swig_ret IBlipPool) {
	var swig_r IBlipPool
	_swig_i_0 := arg1
	swig_r = (IBlipPool)(SwigcptrIBlipPool(C._wrap_IMultiplayer_GetBlipPool_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIMultiplayer) GetPickupPool() (_swig_ret IPickupPool) {
	var swig_r IPickupPool
	_swig_i_0 := arg1
	swig_r = (IPickupPool)(SwigcptrIPickupPool(C._wrap_IMultiplayer_GetPickupPool_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIMultiplayer) GetObjectPool() (_swig_ret IObjectPool) {
	var swig_r IObjectPool
	_swig_i_0 := arg1
	swig_r = (IObjectPool)(SwigcptrIObjectPool(C._wrap_IMultiplayer_GetObjectPool_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIMultiplayer) GetLabelPool() (_swig_ret ITextLabelPool) {
	var swig_r ITextLabelPool
	_swig_i_0 := arg1
	swig_r = (ITextLabelPool)(SwigcptrITextLabelPool(C._wrap_IMultiplayer_GetLabelPool_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIMultiplayer) GetWorld() (_swig_ret IWorld) {
	var swig_r IWorld
	_swig_i_0 := arg1
	swig_r = (IWorld)(SwigcptrIWorld(C._wrap_IMultiplayer_GetWorld_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrIMultiplayer) GetConfig() (_swig_ret IConfig) {
	var swig_r IConfig
	_swig_i_0 := arg1
	swig_r = (IConfig)(SwigcptrIConfig(C._wrap_IMultiplayer_GetConfig_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func DeleteIMultiplayer(arg1 IMultiplayer) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_IMultiplayer_rage_a350b1ffd789f23c(C.uintptr_t(_swig_i_0))
}

type IMultiplayer interface {
	Swigcptr() uintptr
	SwigIsIMultiplayer()
	AddEventHandler(arg2 IEventHandler)
	AddRemoteEventHandler(arg2 Std_string, arg3 Std_function_Sl_void_Sp_IPlayer_Sm__Sc_args_t_SS_const_SA__SP__Sg_)
	GetPlayerPool() (_swig_ret IPlayerPool)
	GetVehiclePool() (_swig_ret IVehiclePool)
	GetColshapePool() (_swig_ret IColshapePool)
	GetCheckpointPool() (_swig_ret ICheckpointPool)
	GetMarkerPool() (_swig_ret IMarkerPool)
	GetBlipPool() (_swig_ret IBlipPool)
	GetPickupPool() (_swig_ret IPickupPool)
	GetObjectPool() (_swig_ret IObjectPool)
	GetLabelPool() (_swig_ret ITextLabelPool)
	GetWorld() (_swig_ret IWorld)
	GetConfig() (_swig_ret IConfig)
}


type SwigcptrIMarkerPool uintptr
type IMarkerPool interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIMarkerPool) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrIPlayerPool uintptr
type IPlayerPool interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIPlayerPool) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint64_t uintptr
type Uint64_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint64_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrIVehicle uintptr
type IVehicle interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIVehicle) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_function_Sl_void_Sp_IPlayer_Sm__Sc_args_t_SS_const_SA__SP__Sg_ uintptr
type Std_function_Sl_void_Sp_IPlayer_Sm__Sc_args_t_SS_const_SA__SP__Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_function_Sl_void_Sp_IPlayer_Sm__Sc_args_t_SS_const_SA__SP__Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrICheckpoint uintptr
type ICheckpoint interface {
	Swigcptr() uintptr;
}
func (p SwigcptrICheckpoint) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrHash_t uintptr
type Hash_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrHash_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint8_t uintptr
type Uint8_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint8_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrIVehiclePool uintptr
type IVehiclePool interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIVehiclePool) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrIColshapePool uintptr
type IColshapePool interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIColshapePool) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrVector3 uintptr
type Vector3 interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVector3) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrArgs_t uintptr
type Args_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrArgs_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrICheckpointPool uintptr
type ICheckpointPool interface {
	Swigcptr() uintptr;
}
func (p SwigcptrICheckpointPool) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrIBlipPool uintptr
type IBlipPool interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIBlipPool) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrIObjectPool uintptr
type IObjectPool interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIObjectPool) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrRage_IPlayer uintptr
type Rage_IPlayer interface {
	Swigcptr() uintptr;
}
func (p SwigcptrRage_IPlayer) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrIPlayer uintptr
type IPlayer interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIPlayer) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrIEntity uintptr
type IEntity interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIEntity) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_string uintptr
type Std_string interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_string) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_u16string uintptr
type Std_u16string interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_u16string) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint32_t uintptr
type Uint32_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint32_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrIColshape uintptr
type IColshape interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIColshape) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrIPickupPool uintptr
type IPickupPool interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIPickupPool) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrITextLabelPool uintptr
type ITextLabelPool interface {
	Swigcptr() uintptr;
}
func (p SwigcptrITextLabelPool) Swigcptr() uintptr {
	return uintptr(p)
}

